runtime: go
runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '1.21'

env: flex
env_variables:
  ENV: 'PRODUCTION'
  TIMEOUT: 2
  JWT_SECRET: 'lovetika3623'
  JWT_REFRESH_SECRET: 'lovemijay3623'
  DB_HOST: '10.61.112.3'
  DB_PORT: '5432'
  DB_USER: 'web-api-postgres'
  DB_PASS: 'Generate92!'
  DB_NAME: 'web_api'
  DB_SSL: 'disable'

network:
  name: default

beta_settings:
  cloud_sql_instances: 'kelvin-web-api:us-central1:web-api-postgres'

liveness_check:
  path: '/health'
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
