runtime: custom
env: flex

instance_class: F1

env_variables:
  DATABASE_URL: 'postgres://postgres:kelvin_web_api_123@/web_api?host=/cloudsql/kelvin-web-api:us-central1:web-api-postgres'
  ENV: 'PRODUCTION'
  TIMEOUT: 2
  JWT_SECRET: 'lovetika3623'
  JWT_REFRESH_SECRET: 'lovemijay3623'
