version: '3.9'
services:
  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - fullstack

  web:
    image: kelvin-rest-api:latest
    container_name: kelvin_rest_api
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgresdb
    volumes:
      - .:/app
    networks:
      - fullstack

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
