FROM golang:1.21.5

# Set destination for COPY
WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/engine/reference/builder/#copy
COPY . ./

CMD ["air", "-c", ".air.toml"]