version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_DB: web_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    network_mode: bridge

  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: kelvin_rest_api
    command: air
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./:/app
    network_mode: bridge
