version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    network_mode: bridge

  app:
    build: .
    container_name: kelvin_rest_api
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - postgresdb
    links:
      - postgresdb
    volumes:
      - .:/app
    network_mode: bridge
